name: login_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Asap
      fonts:
        - asset: 'assets/fonts/asap.ttf'
   
       
        
