name: login_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_secure_storage: ^8.0.0
  overlay_loading_progress: ^1.0.1
  path: ^1.8.3
  sqflite: ^2.2.8+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Asap
      fonts:
        - asset: 'assets/fonts/asap.ttf'
   
       
        
